sudo: required
services:
    - docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm test 

after_success:
    - docker build -t kmahmassani/multi-client ./client
    - docker build -t kmahmassani/multi-nginx ./nginx
    - docker build -t kmahmassani/multi-server ./server
    - docker build -t kmahmassani/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Upload images to docker hub
    - docker push kmahmassani/multi-client
    - docker push kmahmassani/multi-nginx
    - docker push kmahmassani/multi-server
    - docker push kmahmassani/multi-worker